### ISSUE TITLE
How to test from Debian GNU/Linux using g++?

### ISSUE THREAD

**Issue by Villelmo** [PacktPublishing/CPP17-By-Example#1]
I test any example but the result expected is bad. The library don't recognized. 

For example: 

`Book.cpp:1:10: fatal error: Set: No existe el fichero o el directorio
 #include <Set>
          ^~~~~
compilation terminated.
`

_**Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux**_

**Comment by ArjunVarma39** [comment]
Hello @Villelmo

Here is the feedback shared by the author:

To test the code in other environments, such as Linux, the include directives must be changed to hold small letters only. For instance, ```#include <Set>``` must be changed to ```#include <set>```.

Thank you!

**Comment by Villelmo** [comment]
The book was removed from the platform O'reilly.
